Add University Service and Tests
ucsb-cs156-f23/team01-f23-6pm-4 pull request #18
Opened 2023-10-19 03:48 UTC by chelseastoner

In this PR, we add a service that wraps the University API from http://universities.hipolabs.com/search?name={name}

Closes #14

2023-10-19 21:34 UTC, dayvidwang requested changes
overall looks good, I think there is an unused mapper variable (I might have this as well)

2023-10-19 21:34 UTC, dayvidwang commented on src/main/java/edu/ucsb/cs156/spring/backenddemo/services/UniversityQueryService.java
> +    ObjectMapper mapper = new ObjectMapper();
where is mapper used?

2023-10-19 21:42 UTC, dayvidwang commented
overall terrific job

2023-10-19 21:45 UTC, shuyiwan commented
nice work!

2023-10-22 05:20 UTC, shuyiwan approved these changes
Look good to me!

2023-10-24 18:00 UTC, merged